use_frameworks!

target 'ALWBaseViewController_Example' do
  pod 'ALWBaseViewController', :path => '../'

  target 'ALWBaseViewController_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
